version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules # Para evitar sobrescrever os node_modules do container
    environment:
      - CHOKIDAR_USEPOLLING=true # Hot reload
    env_file:
      - .env
    stdin_open: true
    tty: true
