name: 🔍 Validar título do Pull Request

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  validate-title:
    runs-on: [self-hosted]
    steps:
      - name: ⚙️ Verificando título do PR
        uses: actions/github-script@v7
        with:
          script: |
            const title = context.payload.pull_request.title.toLowerCase();
            const allowedPrefixes = ['fix', 'chore', 'docs', 'style', 'refactor', 'test', 'feat'];
            const isValid = allowedPrefixes.some(prefix => title.startsWith(`${prefix}:`));

            if (!isValid) {
              core.setFailed(
                `❌ O título do Pull Request deve começar com um dos seguintes prefixos: ${allowedPrefixes.join(', ')}. Exemplo: "feat: adicionar login"`
              );
            } else {
              core.info('✅ Título do PR está válido.');
            }
